export const GET_TASK_LIST = 'GET_TASK_LIST'
export const HIDDEN_LOADING = 'HIDDEN_LOADING'
export const GET_TASK_LIST_API_ACTION = 'GET_TASK_LIST_API_ACTION'
export const ADD_TASK_LIST_API_ACTION = 'ADD_TASK_LIST_API_ACTION'